main: main.cpp
	g++ main.cpp -O2 -std=c++14 -o main -I../../FHashTable/FHashTable -I../../abseil-cpp -L../../abseil-cpp/build/absl/container -labsl_raw_hash_set -L../../abseil-cpp/build/absl/hash -labsl_hash -labsl_low_level_hash -labsl_city
